### ISSUE TITLE
Using `app` namespace for attributes

### ISSUE THREAD

**Issue by MarcinOrlowski** [maksim88/PasswordEditText#1]
You should not use generic names for your attributes as this simply may conflict with other existing libs (yes, these shall be fixed too). Make it unique like by adding `pet_` prefix to it or so.

**Comment by maksim88** [comment]
Hey,
thanks for your input!

As far as i know the `res-auto` namespace should be used for library projects (gradle takes care of  figuring out the right namespace and does the mapping and therefore my package name should not be hardcoded)

But thinking about having conflicts in attributes (when you use multiple libraries in your projects) I decided to rename my custom attibutes to `pet_iconShow` and `pet_iconHide` :thumbsup:

**Comment by MarcinOrlowski** [comment]
Thanks. My former report was bit too generic, but you got me right (I edited the report for a record), Here's link to explain why prefix is a solution: https://groups.google.com/d/msg/adt-dev/HeM0aptfddY/wLsLF4oxZjcJ
