### ISSUE TITLE
on start password should by hidden

### ISSUE THREAD

**Issue by ms666** [maksim88/PasswordEditText#10]
i think like in subject, when open ex. log activity, password should be hidden.
i add two lines into your project:

141   passwordVisible = true;
142     togglePasswordIconVisibility();

**Comment by maksim88** [comment]
Could you be more specific? You could also show me the xml file of `PasswordEditText` you are using.

But maybe it is just enough to set the inputType in xml eg like this: `android:inputType="textPassword"`

See the sample for more info

**Comment by maksim88** [comment]
I'll close the issue for now, so please reopen if something is still not clear

**Comment by HayTran** [comment]
I used to face that problem.  Do not mix inputType with another properties like  "textFilter" or "textNoSuggestions". Just one properties: android:inputType="textPassword". That will resolve your problem.
