### ISSUE TITLE
Share PassReveal icon with another icon

### ISSUE THREAD

**Issue by jfblanco** [maksim88/PasswordEditText#12]
Hi!, first for all, thanks for answer,

I have a PasswordEditText with an "Info" icon that opens a modal with special information. 

Is there any configuration that I can use two show both icons (info and pass reveal) together? 

Have a nice day!

**Comment by maksim88** [comment]
Hey, 
is your info button also using `drawableRight` for that? If yes then this is currently not possible.
I would just create a horizontal `LinearLayout` and have an `ImageButton` with the info icon next to a `PasswordEditText` to have the same effect
