### ISSUE TITLE
Android support library v.24.2.0 issue

### ISSUE THREAD

**Issue by AShuba** [maksim88/PasswordEditText#14]
After upgraded to Android support library v.24.2.0 icon issue appears.
When user starts type password icon jumps to the center of the edit box.
Reproduced with support library v.24.2.0 only (especially with com.android.support:design:24.2.0)

![screenshot from 2016-08-17 19-25-20](https://cloud.githubusercontent.com/assets/1579321/17756903/2bdad706-64b1-11e6-9bc3-5e4cd15147b5.png)

**Comment by maksim88** [comment]
You are right. TextInputLayout now has the possibility to show the eye icon internally. I'll start looking for a solution shortly

**Comment by maksim88** [comment]
Unfortunately the library right now cannot work due to a bug inside the code of the TextInputLayout.
I opened a ticket some days ago.
https://code.google.com/p/android/issues/detail?id=220503
So for now the lib is not compatible with 24.2.0 and we have to wait for a bugfix on google´s side.

**Comment by maksim88** [comment]
The issue was fixed by the android team (for more info see the bug report)
I also released a new version of the library (`v0.9` is available in `Jitpack` and should be available soon in `jcenter()`)
