### ISSUE TITLE
JitPack

### ISSUE THREAD

**Issue by guisantogui** [maksim88/PasswordEditText#15]
@maksim88,

Could you help me with a problem?
I'm trying to publish an library test build to jitpack, but I didn't figure out what's going wrong, I got the error: No releases found. Try a commit or `-SNAPSHOT`

Do you know how can I manage this.

(Yeah, I know, this is not a PasswordEditText related question, but I would be glad if you could help me)

**Comment by maksim88** [comment]
Hey,

actually you just need to make a release here: `https://github.com/<username>/<library>/releases/new`

After you released it it is actually available via jitpack. You can see it here:
`https://jitpack.io/#maksim88/PasswordEditText`

Afterwards you just need to add the jitpack repo to your `build.gradle`:

```
allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
```

That's it! You add your dependency to the `dependencies` closure and you're done.

**Comment by guisantogui** [comment]
@maksim88 thanks a lot man! I have figured out how to do this!
