### ISSUE TITLE
Make lib obsolete?

### ISSUE THREAD

**Issue by MarcinOrlowski** [maksim88/PasswordEditText#18]
While I understand this may be a bit painful, I suggest to flag this library as obsolete visible way, (i.e. by adding more info in README) as same feature is now provided by `TextInputLayout`.

The point here is that abandoning non-standard libs in favors of standard ones is beneficial for everyone (but author of the former :). And since I do not expect you to work on your lib much, it'd be nice to tell the potential users that this dependency can be avoided in favor of standard libs.

Anyway, thanks for the lib I was using for so long :)

**Comment by maksim88** [comment]
Hey, I guess you are right. 
I have a `NOTE` for quite some time on top of the Readme, but I guess I can make it even more visible because I totally agree that the official way should be the preferred way to go
