### ISSUE TITLE
option to set toggle icon to the left of PasswordEditText

### ISSUE THREAD

**Issue by harikiran-01** [maksim88/PasswordEditText#19]

**Comment by maksim88** [comment]
I'm currently on vacation so I cannot check but all RTL layouts should automatically place the eye on the left side. 
I did not see any need to place it on the other side in non-rtl layouts so it is not possible. 

Also I am not actively developing the library anymore so feel free to fork and implement that functionality which should be easy as the code to move the drawable is already there ( but just guarded with a RTL check right now) 

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
