### ISSUE TITLE
SetError

### ISSUE THREAD

**Issue by guisantogui** [maksim88/PasswordEditText#4]
Hi Maksim,

I really liked your Password Text Field, but i got a problem using it, once I have called the method setError("some error message"), the show/hide icon, becomes invisible, do you have any idea how to fix that?

Thanks, and congratulations for this project.

**Comment by maksim88** [comment]
Hi, you are right.
I checked out the `setError()` code and it actually uses the same approach of setting a drawable on the side as I am, so it overlays it.
I might have a solution in my head that I could try in the next days. 
I'll keep you updated

**Comment by guisantogui** [comment]
Hello @maksim88 do you have any hint that make me workaround this problem?

**Comment by maksim88** [comment]
No, i'm sorry, but I don't have a solution for now..
So ideas are appreciated!

**Comment by guisantogui** [comment]
Ok, thanks I'll look for it!

**Comment by maksim88** [comment]
One idea could maybe be to do something similar to a newly created category inside the Material Design specs:
![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3ZHFxVFJqVy1FOEU/components_textfields_passwordinput.png)
[https://www.google.com/design/spec/components/text-fields.html#text-fields-password-input]

So setError() could just have a red underline and the text could be underneath. 

In the weekend I could look into the possibilities there.

**Comment by maksim88** [comment]
Just found out something:

The solution above is already possible with the `TextInputLayout`.

You just need to wrap the `PasswordEditText` inside a `TextInputLayout` and call:

`pwTextWrapper.setErrorEnabled(true);`

Afterwards if you want to show an error you would call `setError()` on the `pwTextWrapper` which would show the following:
<img width="472" alt="textinputlayout" src="https://cloud.githubusercontent.com/assets/5750253/13791695/9fddef5e-eaee-11e5-81d6-1bfa74528c11.png">

I think  this is the best solution.

**Comment by guisantogui** [comment]
@maksim88 You are the best! I tried it, and it works and I got a more beautiful screen! =)
