### ISSUE TITLE
TextInputLayout doesn't show Error anymore after using the PasswordEditText to show/hide the password

### ISSUE THREAD

**Issue by gotti77** [maksim88/PasswordEditText#8]
Before clicking on the icon the show/hide the password, the `PasswordEditText` and `TextInputLayout` work as expected and is able to show an error. However after clicking on the icon `TextInputLayout.setError("error")` doesn't work anymore.

**Comment by maksim88** [comment]
@gotti77 Can you give me the steps to reproduce?

What I tried:
- `PasswordEditText` is wrapped around a `TextInputLayout`, which is what you have, i suppose.
- `setErrorEnabled(true)` called on the TextInputLayout.
- Calling `setError()` before _or_ after clicking the icon works fine for me (red underline + error text underneath)

My layout:

```
<android.support.design.widget.TextInputLayout
        android:id="@+id/input_layout_password"
        android:layout_width="match_parent"
        android:gravity="start"
        android:layout_marginTop="16dp"
        android:textAlignment="viewStart"
        android:layout_height="wrap_content">

        <com.maksim88.passwordedittext.PasswordEditText
            android:id="@+id/input_password"
            android:gravity="start"
            android:textAlignment="viewStart"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="textPassword"
            android:hint="Password" />
    </android.support.design.widget.TextInputLayout>
```

**Comment by arj154** [comment]
I'm finding issues with this library and setError too. The error message seems to be appearing for me. However it makes the icon for showing and hiding the text disappear. Other times it stops the functionality of being able to toggle show/hide. It might need some testing with the setError.

**Comment by gotti77** [comment]
@maksim88 here my reply:

```
<android.support.design.widget.TextInputLayout
            android:id="@+id/loginActivityPasswordLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.maksim88.passwordedittext.PasswordEditText
                android:id="@+id/loginActivityPassword"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="textPassword"
                android:hint="@string/login_activity_hint_password"
                app:pet_nonMonospaceFont="true"/>

        </android.support.design.widget.TextInputLayout>
```

```
passwordLayout = (TextInputLayout) findViewById(R.id.loginActivityPasswordLayout);
passwordLayout.setError("Error");
passwordLayout.setError(null);
passwordLayout.setError("Error");
```

I don't call `setErrorEnabled(true)` since it will be enabled by setting an error message `!= null`. Setting the error with `null` clears the error again. However this doesn't make any different if I do so like you did. Unfortunately I just recognized that this bug also occurs when using the standard `EditText` and has nothing to do whether I have used the icon to clear/show the password or not. Is there something that I am doing wrong? I just want to set an error message after I cleared one before.

**Comment by gotti77** [comment]
Well it seems that I need to call `setError(null)` together with `setErrorEnabled(false)` to get it work. (c.f. https://code.google.com/p/android/issues/detail?id=194030)

Sorry for the trouble @maksim88. It's not a bug of your PasswordEditText.
