### ISSUE TITLE
Password icon should not always be shown when switching between fragments

### ISSUE THREAD

**Issue by zaiddabaeen** [maksim88/PasswordEditText#9]
Due to:

```
    @Override
    public void onRestoreInstanceState(Parcelable state) {
        SavedState savedState = (SavedState) state;
        super.onRestoreInstanceState(savedState.getSuperState());
        passwordVisible = savedState.isShowingIcon();
        handlePasswordInputVisibility();
        showPasswordVisibilityIndicator(true);
    }
```

When switching between fragments that has the PasswordEditText, the indicator is always shown even if there is no text in the EditText.

A solution would be to comment this line out.

**Comment by maksim88** [comment]
Hey, thanks for your bugreport!

I fixed it in the new version. Could you try to update to `v0.7` or  `v0.8` and reopen if it is still occurring?
